application:
    appName: srs

spring:
    application:
        name: srsservice
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgres://txxhqtqqeeeavl:687e6e6457306d42f38d0feeb5b6c1b7fc231411da8ed7ea39cbde0e23b9ff3d@ec2-54-146-4-66.compute-1.amazonaws.com:5432/d7e4ih8qmge2i7
#        username: srs
#        password: srs
        hikari:
            poolName: Hikari
            auto-commit: false
    jackson:
        date-format: yyyy-MM-dd
        deserialization:
            fail-on-unknown-properties: false
    jpa:
        database: POSTGRESQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    liquibase:
        change-log: classpath:/db/master.xml
#        drop-first: true
server:
    port: 8080
